# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 2739d521d95a7f272071a03efde0aa8c1400bffaa363966d96b3d64dcda897484b335c3bcbf7808ae83e04f59444b1619c1c77a58fef780673f72a24d82605a5

test:
  secret_key_base: 7bb45afac32e5c8db807eac42a4c81b41c9140a373901a7f0d81288556f6d9c3b4ac408bf6c7c52ce6707ed966768fe3b785cee7245b5b13399796f06d16cf03

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
